version: '3.8'

# services:
#   # app:
#   #   build:
#   #     context: .
#   #     dockerfile: Dockerfile
#   #   environment:
#   #     - PORT=${PORT}
#   #   volumes:
#   #     - .:/app
#   #     - .:/app/node_modules
#   #   ports:
#   #     - 3000:3000
#   #   depends_on:
#   #     - db
#   #     - redis
#   #   networks:
#   #     - tcc
# version: '3.1'

services:
  cassandra:
    image: cassandra:latest
    restart: unless-stopped
    ports:
      - 9042:9042
    volumes:
      - ./data/cassandra:/var/lib/cassandra

  redis:
    image: redis:latest
    restart: unless-stopped
    ports:
      - 6379:6379
    volumes:
      - ./data/redis:/data

  app-import:
    build: .
    depends_on:
      - cassandra
      - redis
    volumes:
      - .:/usr/src/app
    command: >
      bash -c "python import_cassandra.py && python import_redis.py"

