version: '3.8'

services:
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   environment:
  #     - PORT=${PORT}
  #   volumes:
  #     - .:/app
  #     - .:/app/node_modules
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - db
  #     - redis
  #   networks:
  #     - tcc

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: tcc
      POSTGRES_PASSWORD: tcc
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'
  
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=tcc@tcc.com
      - PGADMIN_DEFAULT_PASSWORD=tcc
    ports:
      - '5050:80'
    depends_on:
      - db

  redis:
    image: redis:alpine
    command: redis-server --requirepass tcc
    ports:
      - '6379:6379'
